### ISSUE TITLE
Unicode errors on RIS export, suggest to use unicode templates

### ISSUE THREAD

**Issue by computron** [scopus-api/scopus#47] opened 2017-08-30 23:30 UTC
If a ScopusAbstract contains unicode, the .ris property (and probably others like .bibtex) fail. This can be fixed by using a unicode template, e.g.:

```
template = u'''TY  - JOUR
```

with the ```u``` character added for unicode. You may need to repeat for other templates, e.g. bibtex

If you want a test, just try:
```
from scopus import ScopusAbstract
print(ScopusAbstract("2-s2.0-84896986100").ris)
```

**Comment by Michael-E-Rose** [comment] 2017-08-31 00:16
Thanks, that's a good catch.  It indeed causes problems on python 2.7.  Do you want to issue a pull request with changes for `.ris` and other properties where this problem might occur?

**Comment by Michael-E-Rose** [comment] 2017-09-03 22:19
Closed in 44f8f8991e8b60a63feb7849caad0e60f4b7db31.

**Closed by Michael-E-Rose** 2017-09-03 22:19 UTC
Labels: bug

**Comment by Xunius** [comment] 2019-04-22 13:14
Hi,
I'm not actually using this but just came into this from a search.
It seems that the RIS format actually doesn't allow unicode. In the wikipedia page I didn't find anything regarding the allowed chars. But I did find [this pdf](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=17&cad=rja&uact=8&ved=2ahUKEwig2tyA4ePhAhUDFzQIHcKbBMwQFjAQegQIBxAC&url=https%3A%2F%2Fjira.sakaiproject.org%2Fsecure%2Fattachment%2F21845%2FRIS%2BFormat%2BSpecifications.pdf&usg=AOvVaw3SS0L4Pzx5Vk0wYEms_8zW) and this [archived page](https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp) where there is a link to a doc saying basically the same thing as the 1st one, specifically:

> CHARACTERS ALLOWED IN FIELDS
> The characters allowed in the reference ID fields can be in the set "0" through "9," or "A" through "Z."
> The characters allowed in all other fields can be in the set from "space" (character 32) to character 255
> in the ANSI Character Set. Note, however, that the asterisk (character 42) is not allowed in the author,
> keywords or periodical name fields.

So maybe not use the `u''`?

**Comment by Michael-E-Rose** [comment] 2019-04-24 09:13
I think the problem is not actually the encoding, but the presence of non-ANSI characters.  So we would need a transliteration, replacing or removing non-ANSI characters.

I'm not actually sure how many people use the ris-facility, but I doubt it's a lot.  Thus it's not on my priority.  I'm accepting PR's though.

**Comment by Xunius** [comment] 2019-04-24 11:31
On second thought, I do feel that restricting to ascii chars is ridiculous.
